### ISSUE TITLE
Add textarea GUI to fields: Tour Name, Tagline, Subheader, Secondary Sponsor Text

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#17]
We would like the **Tour Name, Tagline, Subheader, Secondary Sponsor Text** fields to have the same text GUI editor that the content area does (without the media fields)

**Comment by etix-aaron** [comment]
this has been added to the [staging server](http://rhppabst17stge.wpengine.com/). please check.

**Comment by sarandi** [comment]
Looks good! On our last call we also discussed changing the code editor to tab view instead of modal/popup view. 

We're also hoping to add one more feature if possible - a font-size dropdown including a range of EM-based sizes from 0.5 - 2.0 in 0.1 increments with 1.2em line-height. Looks like we're using TinyMCE, so here's my best shot at what this would look like in the config:

```
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'fontsizeselect',
  fontsize_formats: "0.5em 0.6em 0.7em 0.8em 0.9em 1.0em 1.1em 1.2em 1.3em 1.4em 1.5em 1.6em 1.7em 1.8em 1.8em 1.9em 2.0em";
});
``
Not sure if it's possible, but might be worth trying using a css font shorthand to add the line-height, like so:
```
.. 0.6em/1.2em 0.7em/1.2em ..
``

If that doesn't work, we could simply add `line-height: 1.2em;` to all associated base selectors in style.css (or wherever it's best served). We would like this change added all instances of the TinyMCE GUI (including #25)

**Comment by etix-aaron** [comment]
This item is on staging and will be pushed to the live site Monday evening (10.29)
