### ISSUE TITLE
Revisionize doesn't publish scheduled event without manually clearing cache

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#21]
This feels likely due to a caching bug, possibly broader than just this issue.

Here's my process and the resulting behavior I'm experiencing:

1. I make a new revision by clicking revisionize
2. I add content - so far, just added a line text to the main content area so I can tell if the content is actually changing (would like to test this further once the below problems are fixed)
3. I schedule the event in the publish box
![image](https://user-images.githubusercontent.com/145392/40505826-1805e076-5f5b-11e8-8f51-45afa4027799.png)

4. I wait for the set time to pass, plus two minutes in case of caching/delay/etc.
5. In a different browser/incognito window, I reload the page - but the old content delivers, not the newly scheduled change. Even a hard refresh (cmd/ctrl+shift+r) doesn't force the site to deliver the new content.
6. In the WP sidebar menu UI I go to WP Engine > General Settings, and press Purge All Caches
7. I return the page (different browser/incognito window), refresh and the correct content is displaying - If I don't purge the cache, the page never presents the correct information

**Comment by etix-aaron** [comment]
This item has been corrected with caching plugin update. Recommend closing.
