### ISSUE TITLE
Events should announce as scheduled

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#22]
We have noticed two cases in which events have not published as scheduled.

Event 1: Highly Suspect
Event 2: Kenny G

Email reports/discussion below
================================================================

Subject: Bug Report
Apr 16, 2018, 1:39 PM

Hi Daniel and Aaron,

We just encountered a bug on the site - 

Our Highly Suspect show was scheduled to go live at Noon today (4/16) but didn't.

To fix this, I changed the Published Status to draft, updated, then changed it back to published, then pressed schedule - and it appeared immediately on the homepage/calendar/etc.

Can someone please look into why this didn't announce?

Thank you.

Sarandi

================================================================

Email Subject: Kenny G Show didn't announce as scheduled
Apr 30, 2018, 1:06 PM
 
Today's Kenny G show set to announce at 11AM CDT didn't go live, similarly to what happened with our Highly Suspect announce.

I'll follow up soon regarding the other outstanding issues but wanted to address this first.

All the fields were set correctly. I first tried clearing the WP Cache but that didn't fix the issue. Below are some screenshots of the settings before we altered anything, and following that is our use case for how we fixed it (differs slightly from what I wrote last time):

Event Settings Screen Shots:

Image 1 (Kenny G is listed as "Scheduled")
https://slack-files.com/T4CSZPMDM-FAFPSFPD1-15abb08e89

Image 2 (Event Timing Announce Setting)
https://slack-files.com/T4CSZPMDM-FAFPSCQ11-5530b16537

Image 3 (Schedule Timing Publish Setting)
https://slack-files.com/T4CSZPMDM-FAFAND0DP-5f35e32baa

================================================================

May 2, 2018, 11:25 AM

Hi Daniel,

Sure thing, sorry about that. Here they are in matching order:

Pressed Edit (on the Status): https://slack-files.com/T4CSZPMDM-FAH5KRVSN-2a2808e9e0
Changed it (Status) to Draft, clicked OK: https://slack-files.com/T4CSZPMDM-FAH9MLLF7-ae3c408eaf
Changed it (Status) back to Scheduled, pressed okay: https://slack-files.com/T4CSZPMDM-FAH5MJER0-2d46a206a6
Then pressed publish, and it went live: https://slack-files.com/T4CSZPMDM-FAGEKBFU0-10f64ab579

**Comment by etix-aaron** [comment]
This item has been corrected with caching plugin update. Recommend closing.
