### ISSUE TITLE
Field for alert box above show content

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#25]
We want a dedicated textarea with a GUI editor that renders text above the show billing/info on a per-event basis.

Here's a preliminary mockup:
https://jsfiddle.net/sarandi/z1fo1gnt/

We will be finalizing the markup on this soon - when complete we would like the markup/css to be copied from the above.

![image](https://user-images.githubusercontent.com/145392/40748394-e141a230-6425-11e8-86d2-af5eb345bbe1.png)

**Comment by etix-aaron** [comment]
this is ready for your review on staging.

**Comment by sarandi** [comment]
This looks like it's done to the specifications in the jsfiddle, though we might need to do a few minor css adjustments. Will discuss with @supergunMKE in the morning prior to our call. Looks like this also addresses #17 .

![image](https://user-images.githubusercontent.com/145392/44127735-603af86a-a004-11e8-8b67-0f0ed920011e.png)

**Comment by sarandi** [comment]
Three changes here that we would like to see, we can roll out the first immediately and work on the others afterward:

1. We would like to see a few CSS changes:

```
.alert {
    border: 5px #900 dotted;
    display: block;
    margin: 3% 0;
    padding: 3% 5%;
    width: 90%;
}
```

That should render close to this:
![image](https://user-images.githubusercontent.com/145392/44234923-7e767600-a16d-11e8-85c0-f7e5488d3b9a.png)


2. We would also like a conditional timing feature added to this. We're thinking two datetime pickers to specify start and stop times. 

**Conditions:**
If neither are set, display the field immediately and indefinitely
If both are set, only display field between the ranges. 
If start is set and stop is unset, only display field after that datetime. 
If start is unset and end is set, display field immediately but disable after the stop time.

3. Finally, we'd like to be able to add our own custom shortcodes à la https://docs.getshortcodes.com/article/61-custom-shortcode
For example, we have numerous variations on changes to shows (cancellations, rescheduling, venue changes, etc.) for which we use a standard set of language. We would like to be able to maintain these via the alert field's textarea GUI under shortcodes > pabst > our custom shortcode(s)

**Comment by etix-aaron** [comment]
@sarandi, the css has been updated on staging.

**Comment by sarandi** [comment]
Looks good, pending changes in #17

**Comment by etix-aaron** [comment]
This item is on staging and will be pushed to the live site Monday evening (10.29)
