### ISSUE TITLE
Cache should allow slides to clear according to scheduled end time

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#26]
Currently, when using the Post Expirator on slides, the slides aren't removed from the slideshow without a clearing the cache manually. This process needs to be automatic.

We recently set a slide with Memorial Day Hours to auto-expire on Monday evening, and it didn't. To fix this, Jason manually removed the slide (did not clear cache). @sarandi has since tested and the issue seems to be that caching doesn't have expiration info related to the slide expiration. 

![image](https://user-images.githubusercontent.com/145392/40743540-6e4b44b0-6417-11e8-96d1-0d249ac7c0a9.png)

**Comment by sarandi** [comment]
Issue resolves after the 10 minute caching max-age. My fear with the generic catch-all plugin is that timing-based caching issues such as this one still will be at the mercy of the 10 minute delay.

**Comment by etix-aaron** [comment]
This item has been corrected with caching plugin update. Recommend closing.
