### ISSUE TITLE
New Slide Dimensions 800x450

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#27]
The site currently trims supplied slide images to 800x400.
We would like to keep this behavior, but change the dimensions to 800x450 pixels.

This would allow us to reuse existing graphics without having to manually scale them.

**Comment by etix-aaron** [comment]
this is updated on the [staging site](http://rhppabst17stge.wpengine.com/). please let us know if we can push live.

**Comment by sarandi** [comment]
Closing this for now as it looks good on Staging and likely on Production, but we're waiting on our team to make the settings change.
