### ISSUE TITLE
Site tries to deliver resources that don't exist and conflict with CORS specifications

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#32]
By opening Google Chrome Dev Tools, I see that basically the same JavaScript error is occurring on two different resources:

1. Access to Font at 'https://9upqp16we5e1z54q2mbfyfol-wpengine.netdna-ssl.com/wp-content/themes/Pabst/WebFont.woff' from origin 'https://pabsttheater.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://pabsttheater.org' is therefore not allowed access. The response had HTTP status code 404.
(index):1 

2. Access to Font at 'https://9upqp16we5e1z54q2mbfyfol-wpengine.netdna-ssl.com/wp-content/themes/Pabst/WebFont.ttf' from origin 'https://pabsttheater.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://pabsttheater.org' is therefore not allowed access. The response had HTTP status code 404.
tribe-events.min.js?ver=4.6:1 

![image](https://user-images.githubusercontent.com/145392/40810115-7156628a-64f2-11e8-8770-3136425288b6.png)

When I try loading either resource, the server NGINX returns a 404 response:
![image](https://user-images.githubusercontent.com/145392/40810326-1397a9be-64f3-11e8-8c51-33b77e744765.png)

**Comment by etix-aaron** [comment]
Etix will is still exploring this issue

**Comment by sarandi** [comment]
Closing this - errors are gone.
