### ISSUE TITLE
Extra arrow displaying in accordions on certain show pages

### ISSUE THREAD

**Issue by ljarvis** [pabsttheater/pabstetix#34]
Example problem page: https://pabsttheater.org/event/maggierogers2018/

![screen shot 2018-08-01 at 9 58 42 am](https://user-images.githubusercontent.com/7968766/43529734-87bdcc34-9571-11e8-98ea-b80a9615ce1d.png)

**Comment by etix-aaron** [comment]
Cannot replicate.  Please provide browser version.
