### ISSUE TITLE
Enhancement to alert box above show content

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#35]
This issue is directly related to #25 and extends its functionality.

Two features we'd like to add:

1. We would like a conditional timing feature added to this. We're thinking two datetime pickers to specify start and stop times.
Conditions:
If neither are set, display the field immediately and indefinitely
If both are set, only display field between the ranges.
If start is set and stop is unset, only display field after that datetime.
If start is unset and end is set, display field immediately but disable after the stop time.

2. We'd like to be able to add our own custom shortcodes à la https://docs.getshortcodes.com/article/61-custom-shortcode
For example, we have numerous variations on changes to shows (cancellations, rescheduling, venue changes, etc.) for which we use a standard set of language. We would like to be able to maintain these via the alert field's textarea GUI under shortcodes > pabst > our custom shortcode(s)

**Comment by etix-aaron** [comment]
This item is on stating and will be pushed to the live site Monday evening (10.29)
