### ISSUE TITLE
Strange Carousel Behavior when switching Slide Dimensions on Production

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#36]
This is related directly to #27 which has been closed, but wanted this all in its own issue as this is a bit detailed.

Usecase:

1. I followed Daniel's directions (from the 20180814 email) to change the slide dimensions
2. Jason removed all active slides and created new slides, using files 1920x1080px (same proportions as 800x450) 
3. The slideshow then borked - as best as I can figure, it rendering the images at full height first, then scaling to 100% of the container:
![screen shot 2018-09-14 at 14 40 16](https://user-images.githubusercontent.com/145392/45572326-943f8f80-b82e-11e8-9e39-1efc82319200.png)
4. I checked in incognito and flushed the cache to see if that would fix - it did not.
5. To fix this, I edited style.css in two places via the WP Theme Editor, though your team may want to review/solve this differently as staging/dev style.css has +~50 lines of diff from production. Here's what I changed:

Lines (Prod) 509-512:
```diff
body .meteor-slides .mslide img {
-width: auto!important;
+width: 100%!important;
-height: 100%!important;
+height: auto!important;
}
```

Lines (Prod) 2947-2949:
```diff
meteor-slides .mslide {
-height: 100%!important; 
+width: 100%!important;
}
```
[full diff, including some other changes](https://www.diffchecker.com/t5UZX2MN)

My thinking here is that by setting the image to scale to the width of the container (width: 100%) THEN setting the height to auto, the feature will automatically scale images correctly, albeit at extra bandwidth to server/users

6. style.css did not clear immediately despite flushing that cache - still took about 10 minutes. Not sure if this is typical behavior but made a [separate issue](37) to document.

**Comment by etix-aaron** [comment]
@sarandi's change has been noted by the dev team and will be respected in future code updates. Recommend closing ticket,
