### ISSUE TITLE
style.css doesn't get flushed when the cache is cleared

### ISSUE THREAD

**Issue by sarandi** [pabsttheater/pabstetix#37]
I updated some [CSS via the WP Theme Editor](36) - the changes didn't take effect immediately so I flushed the cache, but that didn't work either It took 10 minutes to clear when we were expecting an immediate update.

**Comment by etix-aaron** [comment]
We found that style.css changes under "Appearance>>Editor" reflect on frontend without purging the cache. Please double check us, but i believe we can close this ticket.
